title: Felipe Arancibia Carrasco
logo: /assets/img/felipe_face.jpg
description: Me considero proactivo, analítico y gran capacidad de trabajar en equipo. Buena disposición, tolerante al trabajo bajo presión, comprometido en la resolución de problemas y gran interés en aprender.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
